- name: Configure prometheus.
  template:
    src: "{{ templates_dir }}/{{ item }}.j2"
    dest: "{{ prometheus_config_dir }}/{{ item }}"
    backup: true
  with_items: "{{ prometheus_config_file }}"
  notify: Restart prometheus