- name: Install some packages.
  apt:
    name: "{{ some_packages }}"
    state: present

- name: Install apache2 packages.
  apt:
    name: "{{ apache_packages }}"
    state: present
  notify: Disable apache2
