- name: Install needed packages.
  apt:
    name: "{{ needed_packages }}"
    state: present

- name: Install apache2 packages.
  apt:
    name: "{{ apache_packages }}"
    state: present
  notify: Disable apache2
